add_newline = false
command_timeout = 750
format = """
$directory\
$git_branch$git_state$git_status\
$elixir$ruby$nodejs\
$cmd_duration
$character
"""

[directory]
truncation_symbol = "…/"
truncate_to_repo = true
style = "white"

[git_branch]
format = "[ $branch](cyan) "

[git_status]
style = "yellow"

[elixir]
format = '[ $otp_version](red) [ $version](purple) '

[ruby]
format = "[ $version](red) "

[nodejs]
format = "[ $version](green) "

[cmd_duration]
show_milliseconds = true
format = "[ $duration](yellow) "
